export const locations = [
  {
    accountId: "APL001",
    account: "Apple",
    locationIsActive: true,
    eclipsePassword: "********",
    accountLocations: ["MAIN HALLWAY (MAIN HALLWAY)", "EXHIBIT HALL (EXHIBIT HALL)", "FRONT ENTRANCE (FRONT ENTRANCE)"],
    locationHeaderBackgroundColor: "Pink",
    locationName: "WAREHOUSE",
    locationDescription: "WAREHOUSE area for Apple storage and operations",
    displayActiveLocationOnly: false,
    deactivateFromLocationToLocation: true,
    fieldToSelect: "Option 2"
  },
  {
    accountId: "SAM001",
    account: "Samsung",
    accountLampGuidePageHeaderText: "Samsung Product Catalog",
    accountSpecialShippingInstructions: "Handle with care. Keep electronics away from magnets.",
    accountLocations: ["SALES FLOOR WEST (SALES FLOOR WEST)", "TECH STORAGE (TECH STORAGE)", "MEETING ROOM (MEETING ROOM)", "CASH WRAP (CASH WRAP)"],
    locationHeaderBackgroundColor: "Purple",
    locationIsActive: true,
    locationName: "BACKROOM",
    locationDescription: "BACKROOM area for Samsung storage and operations",
    displayActiveLocationOnly: true,
    deactivateFromLocationToLocation: true,
    fieldToSelect: "N/A"
  },
  {
    accountId: "ADD001",
    account: "Adidas",
    accountSpecialShippingInstructions: "Ensure shipment is secure and weather-resistant.",
    accountLocations: ["SECURITY ROOM (SECURITY ROOM)", "BASEMENT (BASEMENT)", "MEETING ROOM (MEETING ROOM)"],
    locationHeaderBackgroundColor: "Purple",
    locationIsActive: false,
    locationName: "SHOWROOM",
    locationDescription: "SHOWROOM area for Adidas storage and operations",
    displayActiveLocationOnly: false,
    deactivateFromLocationToLocation: true,
    fieldToSelect: "Option 3"
  },
  {
    accountId: "NIK001",
    account: "Nike",
    accountLampGuidePageHeaderText: "Nike Product Catalog",
    accountSpecialShippingInstructions: "Ensure packages are securely sealed and dry.",
    accountLocations: ["BACK OFFICE (BACK OFFICE)", "SERVER ROOM (SERVER ROOM)", "BATHROOM/SALES OFFICE (BATHROOM/SALES OFFICE)"],
    locationHeaderBackgroundColor: "Teal",
    locationIsActive: false,
    locationName: "OFFICE",
    locationDescription: "OFFICE area for Nike storage and operations",
    displayActiveLocationOnly: true,
    deactivateFromLocationToLocation: true,
    fieldToSelect: "Option 1"
  },
  {
    accountId: "GOO001",
    account: "Google",
    accountSpecialShippingInstructions: "Ensure timely delivery to meet high-demand project deadlines.",
    accountLocations: ["EVENT SPACE (EVENT SPACE)", "BREAK AREA (BREAK AREA)", "BATHROOM/SALES OFFICE (BATHROOM/SALES OFFICE)", "CAFETERIA (CAFETERIA)", "CASH WRAP/ENTRANCE (CASH WRAP/ENTRANCE)"],
    locationHeaderBackgroundColor: "Red",
    locationIsActive: true,
    locationName: "BACKROOM",
    locationDescription: "BACKROOM area for Google storage and operations",
    displayActiveLocationOnly: false,
    deactivateFromLocationToLocation: false,
    fieldToSelect: "Option 3"
  },
  {
    accountId: "MIC001",
    account: "Microsoft",
    accountSpecialShippingInstructions: "Ensure all items are securely packed for tech equipment safety.",
    accountLocations: ["SERVER ROOM (SERVER ROOM)", "FRONT ENTRANCE (FRONT ENTRANCE)", "BACKROOM/SALES FLOOR (BACKROOM/SALES FLOOR)", "CASH WRAP/ENTRANCE (CASH WRAP/ENTRANCE)"],
    locationHeaderBackgroundColor: "Brown",
    locationIsActive: false,
    locationName: "SHOWROOM",
    locationDescription: "SHOWROOM area for Microsoft storage and operations",
    displayActiveLocationOnly: true,
    deactivateFromLocationToLocation: true,
    fieldToSelect: "Option 1"
  },
  {
    accountId: "TES001",
    account: "Tesla",
    accountLampGuidePageHeaderText: "Tesla Product Catalog",
    accountSpecialShippingInstructions: "Handle items carefully. Fragile EV parts.",
    accountLocations: ["RESTROOM 1 (RESTROOM 1)", "SECURITY ROOM (SECURITY ROOM)", "CASH OFFICE/BACK HALLWAY/BACK ROOM"],
    locationHeaderBackgroundColor: "Brown",
    locationIsActive: false,
    locationName: "WAREHOUSE",
    locationDescription: "WAREHOUSE area for Tesla storage and operations",
    displayActiveLocationOnly: false,
    deactivateFromLocationToLocation: true,
    fieldToSelect: "Option 2"
  },
  {
    accountId: "FBK001",
    account: "Facebook",
    accountLampGuidePageHeaderText: "Facebook Product Catalog",
    accountSpecialShippingInstructions: "Prioritize delivery for media-focused events.",
    accountLocations: ["BELOW BLEACHERS (BELOW BLEACHERS)"],
    locationHeaderBackgroundColor: "Silver",
    locationIsActive: true,
    locationName: "FLOOR",
    locationDescription: "FLOOR area for Facebook storage and operations",
    displayActiveLocationOnly: true,
    deactivateFromLocationToLocation: false,
    fieldToSelect: "Option 2"
  },
  {
    accountId: "AMZ001",
    account: "Amazon",
    accountLampGuidePageHeaderText: "Amazon Product Catalog",
    accountSpecialShippingInstructions: "Ensure expedited shipping for Prime customers.",
    accountLocations: ["BASEMENT CIRCULATION; BASEMENT TEST & CREATE; BOH", "BATH ROOM (BATH ROOM)", "CASH WRAP (CASH WRAP)"],
    locationHeaderBackgroundColor: "Brown",
    locationIsActive: false,
    locationName: "OFFICE",
    locationDescription: "OFFICE area for Amazon storage and operations",
    displayActiveLocationOnly: false,
    deactivateFromLocationToLocation: false,
    fieldToSelect: "Option 1"
  },
  {
    accountId: "SON001",
    account: "Sony",
    accountLampGuidePageHeaderText: "Sony Product Catalog",
    accountSpecialShippingInstructions: "Handle with care. Electronics and fragile products.",
    accountLocations: ["BATH ROOM (BATH ROOM)", "BREAK ROOM/OFFICE (BREAK ROOM/OFFICE)", "CASH WRAP (CASH WRAP)"],
    locationHeaderBackgroundColor: "Silver",
    locationIsActive: true,
    locationName: "FLOOR",
    locationDescription: "FLOOR area for Sony storage and operations",
    displayActiveLocationOnly: true,
    deactivateFromLocationToLocation: false,
    fieldToSelect: "Option 2"
  },
  {
    accountId: "LG001",
    account: "LG",
    accountLampGuidePageHeaderText: "LG Product Catalog",
    accountSpecialShippingInstructions: "Ensure all electronic parts are well-protected.",
    accountLocations: ["MAIN HALLWAY (MAIN HALLWAY)", "BREAK AREA (BREAK AREA)", "MAINTENANCE ROOM (MAINTENANCE ROOM)"],
    locationHeaderBackgroundColor: "Gray",
    locationIsActive: false,
    locationName: "SHOWROOM",
    locationDescription: "SHOWROOM area for LG storage and operations",
    displayActiveLocationOnly: true,
    deactivateFromLocationToLocation: true,
    fieldToSelect: "Option 3"
  },
  {
    accountId: "PUM001",
    account: "Puma",
    accountSpecialShippingInstructions: "Ensure proper handling of footwear and apparel.",
    accountLocations: ["SALES FLOOR WEST (SALES FLOOR WEST)", "CASH WRAP/ENTRANCE (CASH WRAP/ENTRANCE)", "BATHROOM/SALES OFFICE (BATHROOM/SALES OFFICE)", "SALES FLOOR EAST (SALES FLOOR EAST)"],
    locationHeaderBackgroundColor: "Indigo",
    locationIsActive: true,
    locationName: "FLOOR",
    locationDescription: "FLOOR area for Puma storage and operations",
    displayActiveLocationOnly: true,
    deactivateFromLocationToLocation: false,
    fieldToSelect: "N/A"
  },
  {
    accountId: "UAM001",
    account: "Under Armour",
    accountSpecialShippingInstructions: "Handle with care, especially for athletic gear.",
    accountLocations: ["FRONT ENTRANCE (FRONT ENTRANCE)", "ELECTRICAL ROOM (ELECTRICAL ROOM)", "BREAK ROOM/OFFICE (BREAK ROOM/OFFICE)"],
    locationHeaderBackgroundColor: "Pink",
    locationIsActive: false,
    locationName: "FLOOR",
    locationDescription: "FLOOR area for Under Armour storage and operations",
    displayActiveLocationOnly: false,
    deactivateFromLocationToLocation: false,
    fieldToSelect: "N/A"
  },
  {
    accountId: "HUA001",
    account: "Huawei",
    accountSpecialShippingInstructions: "Ensure all tech components are secure during shipping.",
    accountLocations: ["BACKROOM/SALES FLOOR (BACKROOM/SALES FLOOR)", "RESTROOM 1 (RESTROOM 1)", "CASH OFFICE/BACK HALLWAY/BACK ROOM"],
    locationHeaderBackgroundColor: "Silver",
    locationIsActive: false,
    locationName: "SHOWROOM",
    locationDescription: "SHOWROOM area for Huawei storage and operations",
    displayActiveLocationOnly: false,
    deactivateFromLocationToLocation: false,
    fieldToSelect: "N/A"
  }
]