export const stores = [
 // Apple Stores
 {
  storeId: "APLSTR001",
  accountId: "APL001",
  storeName: "Apple Store 1",
  storeNumber: "001",
  eclipseId: "APLSTR001",
  isStoreActive: true,
  addressLine1: "123 Fifth Avenue",
  addressLine2: "",
  city: "New York",
  stateRegion: "NY",
  postalCode: "10001",
  country: "USA",
  storeContact: "John Doe",
  storeTelephone: "123-456-7890",
  storeFax: "123-456-7891",
  storeEmail: "store1@apple.com",
  storeBuildDate: "2020-01-01",
  storeBuildoutTicketNumber: "APL001-001",
  associatedProfile: "Apple Retail",
  serviceProviderStoreId: "APLNY001",
  eclipseStoreReleaseId: "APLREL001",
  hideStoreFromAllUsers: false,
  onlyBidOrdersCanBePlaced: false,
  shipToAddressRequired: true,
  fmsBillTo: "APLFMS001",
  fmsShipTo: "APLFMS001",
  fmsType: "CLM"
 },
 {
  storeId: "APLSTR002",
  accountId: "APL001",
  storeName: "Apple Store 2",
  storeNumber: "002",
  eclipseId: "APLSTR002",
  isStoreActive: true,
  addressLine1: "189 The Grove Dr",
  addressLine2: "",
  city: "Los Angeles",
  stateRegion: "CA",
  postalCode: "90036",
  country: "USA",
  storeContact: "Jane Smith",
  storeTelephone: "987-654-3210",
  storeFax: "987-654-3211",
  storeEmail: "store2@apple.com",
  storeBuildDate: "2021-03-15",
  storeBuildoutTicketNumber: "APL001-002",
  associatedProfile: "Apple Retail",
  serviceProviderStoreId: "APLLA001",
  eclipseStoreReleaseId: "APLREL002",
  hideStoreFromAllUsers: false,
  onlyBidOrdersCanBePlaced: false,
  shipToAddressRequired: true,
  fmsBillTo: "APLFMS002",
  fmsShipTo: "APLFMS002",
  fmsType: "CLM"
 },

 // Samsung Stores
 {
  storeId: "SAMSTR001",
  accountId: "SAM001",
  storeName: "Samsung Store 1",
  storeNumber: "001",
  eclipseId: "SAMSTR001",
  isStoreActive: true,
  addressLine1: "123 Gangnam-daero",
  addressLine2: "",
  city: "Seoul",
  stateRegion: "Seoul",
  postalCode: "06351",
  country: "South Korea",
  storeContact: "Kim Min-jun",
  storeTelephone: "111-222-3333",
  storeFax: "111-222-3334",
  storeEmail: "store1@samsung.com",
  storeBuildDate: "2019-11-01",
  storeBuildoutTicketNumber: "SAM001-001",
  associatedProfile: "Samsung Retail",
  serviceProviderStoreId: "SAMSEOUL001",
  eclipseStoreReleaseId: "SAMREL001",
  hideStoreFromAllUsers: false,
  onlyBidOrdersCanBePlaced: false,
  shipToAddressRequired: true,
  fmsBillTo: "SAMFMS001",
  fmsShipTo: "SAMFMS001",
  fmsType: "CLM"
 },
 {
  storeId: "SAMSTR002",
  accountId: "SAM001",
  storeName: "Samsung Store 2",
  storeNumber: "002",
  eclipseId: "SAMSTR002",
  isStoreActive: true,
  addressLine1: "456 Haeundae-ro",
  addressLine2: "",
  city: "Busan",
  stateRegion: "Busan",
  postalCode: "48099",
  country: "South Korea",
  storeContact: "Park Ji-soo",
  storeTelephone: "222-333-4444",
  storeFax: "222-333-4445",
  storeEmail: "store2@samsung.com",
  storeBuildDate: "2020-06-15",
  storeBuildoutTicketNumber: "SAM001-002",
  associatedProfile: "Samsung Retail",
  serviceProviderStoreId: "SAMBUSAN001",
  eclipseStoreReleaseId: "SAMREL002",
  hideStoreFromAllUsers: false,
  onlyBidOrdersCanBePlaced: false,
  shipToAddressRequired: true,
  fmsBillTo: "SAMFMS002",
  fmsShipTo: "SAMFMS002",
  fmsType: "CLM"
 },

 // Adidas Stores
 {
  storeId: "ADDSTR001",
  accountId: "ADD001",
  storeName: "ADIDAS AMERICA INC - PORTLAND",
  storeNumber: "001",
  eclipseId: "ADDSTR001",
  isStoreActive: true,
  addressLine1: "5055 N Greeley Ave",
  addressLine2: "",
  city: "Portland",
  stateRegion: "OR",
  postalCode: "97217",
  country: "USA",
  storeContact: "Michael Johnson",
  storeTelephone: "333-444-5555",
  storeFax: "333-444-5556",
  storeEmail: "portland@adidas.com",
  storeBuildDate: "2018-09-01",
  storeBuildoutTicketNumber: "ADD001-001",
  associatedProfile: "Adidas Retail",
  serviceProviderStoreId: "ADDPDX001",
  eclipseStoreReleaseId: "ADDREL001",
  hideStoreFromAllUsers: false,
  onlyBidOrdersCanBePlaced: false,
  shipToAddressRequired: true,
  fmsBillTo: "ADDFMS001",
  fmsShipTo: "ADDFMS001",
  fmsType: "CLM"
 },
 {
  storeId: "ADDSTR002",
  accountId: "ADD001",
  storeName: "ADIDAS EUROPE INC - BERLIN",
  storeNumber: "002",
  eclipseId: "ADDSTR002",
  isStoreActive: true,
  addressLine1: "Tauentzienstraße 15",
  addressLine2: "",
  city: "Berlin",
  stateRegion: "Berlin",
  postalCode: "10789",
  country: "Germany",
  storeContact: "Anna Müller",
  storeTelephone: "444-555-6666",
  storeFax: "444-555-6667",
  storeEmail: "berlin@adidas.com",
  storeBuildDate: "2019-03-15",
  storeBuildoutTicketNumber: "ADD001-002",
  associatedProfile: "Adidas Retail",
  serviceProviderStoreId: "ADDBER001",
  eclipseStoreReleaseId: "ADDREL002",
  hideStoreFromAllUsers: false,
  onlyBidOrdersCanBePlaced: false,
  shipToAddressRequired: true,
  fmsBillTo: "ADDFMS002",
  fmsShipTo: "ADDFMS002",
  fmsType: "CLM"
 },

 // Nike Stores
 {
  storeId: "NIKSTR001",
  accountId: "NIK001",
  storeName: "Nike Store NYC",
  storeNumber: "001",
  eclipseId: "NIKSTR001",
  isStoreActive: true,
  addressLine1: "650 Fifth Avenue",
  addressLine2: "",
  city: "New York",
  stateRegion: "NY",
  postalCode: "10019",
  country: "USA",
  storeContact: "Sarah Thompson",
  storeTelephone: "555-666-7777",
  storeFax: "555-666-7778",
  storeEmail: "nyc@nike.com",
  storeBuildDate: "2017-11-01",
  storeBuildoutTicketNumber: "NIK001-001",
  associatedProfile: "Nike Retail",
  serviceProviderStoreId: "NIKNY001",
  eclipseStoreReleaseId: "NIKREL001",
  hideStoreFromAllUsers: false,
  onlyBidOrdersCanBePlaced: false,
  shipToAddressRequired: true,
  fmsBillTo: "NIKFMS001",
  fmsShipTo: "NIKFMS001",
  fmsType: "CLM"
 },
 {
  storeId: "NIKSTR002",
  accountId: "NIK001",
  storeName: "Nike Store LA",
  storeNumber: "002",
  eclipseId: "NIKSTR002",
  isStoreActive: true,
  addressLine1: "189 The Grove Dr",
  addressLine2: "Suite K80",
  city: "Los Angeles",
  stateRegion: "CA",
  postalCode: "90036",
  country: "USA",
  storeContact: "David Brown",
  storeTelephone: "666-777-8888",
  storeFax: "666-777-8889",
  storeEmail: "la@nike.com",
  storeBuildDate: "2018-05-15",
  storeBuildoutTicketNumber: "NIK001-002",
  associatedProfile: "Nike Retail",
  serviceProviderStoreId: "NIKLA001",
  eclipseStoreReleaseId: "NIKREL002",
  hideStoreFromAllUsers: false,
  onlyBidOrdersCanBePlaced: false,
  shipToAddressRequired: true,
  fmsBillTo: "NIKFMS002",
  fmsShipTo: "NIKFMS002",
  fmsType: "CLM"
 },

 // Google Stores
 {
  storeId: "GOOSTR001",
  accountId: "GOO001",
  storeName: "Google Store 1",
  storeNumber: "001",
  eclipseId: "GOOSTR001",
  isStoreActive: true,
  addressLine1: "1600 Amphitheatre Parkway",
  addressLine2: "",
  city: "Mountain View",
  stateRegion: "CA",
  postalCode: "94043",
  country: "USA",
  storeContact: "Emily Chen",
  storeTelephone: "777-888-9999",
  storeFax: "777-888-9990",
  storeEmail: "store1@google.com",
  storeBuildDate: "2021-07-01",
  storeBuildoutTicketNumber: "GOO001-001",
  associatedProfile: "Google Retail",
  serviceProviderStoreId: "GOOMV001",
  eclipseStoreReleaseId: "GOOREL001",
  hideStoreFromAllUsers: false,
  onlyBidOrdersCanBePlaced: false,
  shipToAddressRequired: true,
  fmsBillTo: "GOOFMS001",
  fmsShipTo: "GOOFMS001",
  fmsType: "CLM"
 },
 {
  storeId: "GOOSTR002",
  accountId: "GOO001",
  storeName: "Google Store 2",
  storeNumber: "002",
  eclipseId: "GOOSTR002",
  isStoreActive: true,
  addressLine1: "123 Buckingham Palace Road",
  addressLine2: "",
  city: "London",
  stateRegion: "London",
  postalCode: "SW1W 9SH",
  country: "UK",
  storeContact: "James Wilson",
  storeTelephone: "888-999-0000",
  storeFax: "888-999-0001",
  storeEmail: "store2@google.com",
  storeBuildDate: "2022-01-15",
  storeBuildoutTicketNumber: "GOO001-002",
  associatedProfile: "Google Retail",
  serviceProviderStoreId: "GOOLON001",
  eclipseStoreReleaseId: "GOOREL002",
  hideStoreFromAllUsers: false,
  onlyBidOrdersCanBePlaced: false,
  shipToAddressRequired: true,
  fmsBillTo: "GOOFMS002",
  fmsShipTo: "GOOFMS002",
  fmsType: "CLM"
 },

 // Microsoft Stores
 {
  storeId: "MICSTR001",
  accountId: "MIC001",
  storeName: "Microsoft Store 1",
  storeNumber: "001",
  eclipseId: "MICSTR001",
  isStoreActive: true,
  addressLine1: "One Microsoft Way",
  addressLine2: "",
  city: "Redmond",
  stateRegion: "WA",
  postalCode: "98052",
  country: "USA",
  storeContact: "Robert Johnson",
  storeTelephone: "999-000-1111",
  storeFax: "999-000-1112",
  storeEmail: "store1@microsoft.com",
  storeBuildDate: "2020-08-01",
  storeBuildoutTicketNumber: "MIC001-001",
  associatedProfile: "Microsoft Retail",
  serviceProviderStoreId: "MICRED001",
  eclipseStoreReleaseId: "MICREL001",
  hideStoreFromAllUsers: false,
  onlyBidOrdersCanBePlaced: false,
  shipToAddressRequired: true,
  fmsBillTo: "MICFMS001",
  fmsShipTo: "MICFMS001",
  fmsType: "CLM"
 }, 
 {
  storeId: "MICSTR002",
  accountId: "MIC001",
  storeName: "Microsoft Store 2",
  storeNumber: "002",
  eclipseId: "MICSTR002",
  isStoreActive: true,
  addressLine1: "2-11-3 Meguro",
  addressLine2: "Meguro City",
  city: "Tokyo",
  stateRegion: "Tokyo",
  postalCode: "153-0063",
  country: "Japan",
  storeContact: "Yuki Tanaka",
  storeTelephone: "000-111-2222",
  storeFax: "000-111-2223",
  storeEmail: "store2@microsoft.com",
  storeBuildDate: "2021-02-15",
  storeBuildoutTicketNumber: "MIC001-002"
 },

 // Tesla Stores
 {
  storeId: "TESSTR001",
  accountId: "TES001",
  storeName: "Tesla Store 1",
  storeNumber: "001",
  eclipseId: "TESSTR001",
  isStoreActive: true,
  addressLine1: "999 Van Ness Ave",
  addressLine2: "",
  city: "San Francisco",
  stateRegion: "CA",
  postalCode: "94109",
  country: "USA",
  storeContact: "Elon Musk Jr.",
  storeTelephone: "111-222-3333",
  storeFax: "111-222-3334",
  storeEmail: "sf@tesla.com",
  storeBuildDate: "2019-05-01",
  storeBuildoutTicketNumber: "TES001-001",
  associatedProfile: "Tesla Retail",
  serviceProviderStoreId: "TESSF001",
  eclipseStoreReleaseId: "TESREL001",
  hideStoreFromAllUsers: false,
  onlyBidOrdersCanBePlaced: false,
  shipToAddressRequired: true,
  fmsBillTo: "TESFMS001",
  fmsShipTo: "TESFMS001",
  fmsType: "CLM"
 },
 {
  storeId: "TESSTR002",
  accountId: "TES001",
  storeName: "Tesla Store 2",
  storeNumber: "002",
  eclipseId: "TESSTR002",
  isStoreActive: true,
  addressLine1: "Kurfürstendamm 216",
  addressLine2: "",
  city: "Berlin",
  stateRegion: "Berlin",
  postalCode: "10719",
  country: "Germany",
  storeContact: "Hans Schmidt",
  storeTelephone: "222-333-4444",
  storeFax: "222-333-4445",
  storeEmail: "berlin@tesla.com",
  storeBuildDate: "2020-09-15",
  storeBuildoutTicketNumber: "TES001-002",
  associatedProfile: "Tesla Retail",
  serviceProviderStoreId: "TESBER001",
  eclipseStoreReleaseId: "TESREL002",
  hideStoreFromAllUsers: false,
  onlyBidOrdersCanBePlaced: false,
  shipToAddressRequired: true,
  fmsBillTo: "TESFMS002",
  fmsShipTo: "TESFMS002",
  fmsType: "CLM"
 },

 // Facebook Store
 {
  storeId: "FBKSTR001",
  accountId: "FBK001",
  storeName: "Facebook Store 1",
  storeNumber: "001",
  eclipseId: "FBKSTR001",
  isStoreActive: true,
  addressLine1: "1 Hacker Way",
  addressLine2: "",
  city: "Menlo Park",
  stateRegion: "CA",
  postalCode: "94025",
  country: "USA",
  storeContact: "Mark Zuckerberg Jr.",
  storeTelephone: "333-444-5555",
  storeFax: "333-444-5556",
  storeEmail: "store1@facebook.com",
  storeBuildDate: "2022-03-01",
  storeBuildoutTicketNumber: "FBK001-001",
  associatedProfile: "Facebook Retail",
  serviceProviderStoreId: "FBKMP001",
  eclipseStoreReleaseId: "FBKREL001",
  hideStoreFromAllUsers: false,
  onlyBidOrdersCanBePlaced: false,
  shipToAddressRequired: true,
  fmsBillTo: "FBKFMS001",
  fmsShipTo: "FBKFMS001",
  fmsType: "CLM"
 },

 // Amazon Store
 {
  storeId: "AMZSTR001",
  accountId: "AMZ001",
  storeName: "Amazon Store 1",
  storeNumber: "001",
  eclipseId: "AMZSTR001",
  isStoreActive: true,
  addressLine1: "410 Terry Ave N",
  addressLine2: "",
  city: "Seattle",
  stateRegion: "WA",
  postalCode: "98109",
  country: "USA",
  storeContact: "Jeff Bezos Jr.",
  storeTelephone: "444-555-6666",
  storeFax: "444-555-6667",
  storeEmail: "store1@amazon.com",
  storeBuildDate: "2021-11-01",
  storeBuildoutTicketNumber: "AMZ001-001",
  associatedProfile: "Amazon Retail",
  serviceProviderStoreId: "AMZSEA001",
  eclipseStoreReleaseId: "AMZREL001",
  hideStoreFromAllUsers: false,
  onlyBidOrdersCanBePlaced: false,
  shipToAddressRequired: true,
  fmsBillTo: "AMZFMS001",
  fmsShipTo: "AMZFMS001",
  fmsType: "CLM"
 },

 // Sony Store
 {
  storeId: "SONSTR001",
  accountId: "SON001",
  storeName: "Sony Store 1",
  storeNumber: "001",
  eclipseId: "SONSTR001",
  isStoreActive: true,
  addressLine1: "1-7-1 Konan",
  addressLine2: "Minato-ku",
  city: "Tokyo",
  stateRegion: "Tokyo",
  postalCode: "108-0075",
  country: "Japan",
  storeContact: "Kenichiro Yoshida Jr.",
  storeTelephone: "555-666-7777",
  storeFax: "555-666-7778",
  storeEmail: "store1@sony.com",
  storeBuildDate: "2020-07-15",
  storeBuildoutTicketNumber: "SON001-001",
  associatedProfile: "Sony Retail",
  serviceProviderStoreId: "SONTOK001",
  eclipseStoreReleaseId: "SONREL001",
  hideStoreFromAllUsers: false,
  onlyBidOrdersCanBePlaced: false,
  shipToAddressRequired: true,
  fmsBillTo: "SONFMS001",
  fmsShipTo: "SONFMS001",
  fmsType: "CLM"
 },

 // LG Store
 {
  storeId: "LGSTR001",
  accountId: "LG001",
  storeName: "LG Store 1",
  storeNumber: "001",
  eclipseId: "LGSTR001",
  isStoreActive: true,
  addressLine1: "128 Yeoui-daero",
  addressLine2: "Yeongdeungpo-gu",
  city: "Seoul",
  stateRegion: "Seoul",
  postalCode: "07336",
  country: "South Korea",
  storeContact: "Koo Kwang-mo Jr.",
  storeTelephone: "666-777-8888",
  storeFax: "666-777-8889",
  storeEmail: "store1@lg.com",
  storeBuildDate: "2021-04-01",
  storeBuildoutTicketNumber: "LG001-001",
  associatedProfile: "LG Retail",
  serviceProviderStoreId: "LGSEO001",
  eclipseStoreReleaseId: "LGREL001",
  hideStoreFromAllUsers: false,
  onlyBidOrdersCanBePlaced: false,
  shipToAddressRequired: true,
  fmsBillTo: "LGFMS001",
  fmsShipTo: "LGFMS001",
  fmsType: "CLM"
 },

 // Puma Store
 {
  storeId: "PUMSTR001",
  accountId: "PUM001",
  storeName: "Puma Store 1",
  storeNumber: "001",
  eclipseId: "PUMSTR001",
  isStoreActive: true,
  addressLine1: "Würzburger Str. 13",
  addressLine2: "",
  city: "Herzogenaurach",
  stateRegion: "Bavaria",
  postalCode: "91074",
  country: "Germany",
  storeContact: "Bjørn Gulden Jr.",
  storeTelephone: "777-888-9999",
  storeFax: "777-888-9990",
  storeEmail: "store1@puma.com",
  storeBuildDate: "2019-08-15",
  storeBuildoutTicketNumber: "PUM001-001",
  associatedProfile: "Puma Retail",
  serviceProviderStoreId: "PUMHER001",
  eclipseStoreReleaseId: "PUMREL001",
  hideStoreFromAllUsers: false,
  onlyBidOrdersCanBePlaced: false,
  shipToAddressRequired: true,
  fmsBillTo: "PUMFMS001",
  fmsShipTo: "PUMFMS001",
  fmsType: "CLM"
 },

 // Under Armour Store
 {
  storeId: "UAMSTR001",
  accountId: "UAM001",
  storeName: "Under Armour Store 1",
  storeNumber: "001",
  eclipseId: "UAMSTR001",
  isStoreActive: true,
  addressLine1: "500 E Pratt St",
  addressLine2: "",
  city: "Baltimore",
  stateRegion: "MD",
  postalCode: "21202",
  country: "USA",
  storeContact: "Kevin Plank Jr.",
  storeTelephone: "888-999-0000",
  storeFax: "888-999-0001",
  storeEmail: "store1@underarmour.com",
  storeBuildDate: "2020-02-01",
  storeBuildoutTicketNumber: "UAM001-001",
  associatedProfile: "Under Armour Retail",
  serviceProviderStoreId: "UAMBAL001",
  eclipseStoreReleaseId: "UAMREL001",
  hideStoreFromAllUsers: false,
  onlyBidOrdersCanBePlaced: false,
  shipToAddressRequired: true,
  fmsBillTo: "UAMFMS001",
  fmsShipTo: "UAMFMS001",
  fmsType: "CLM"
 },

 // Huawei Store
 {
  storeId: "HUASTR001",
  accountId: "HUA001",
  storeName: "Huawei Store 1",
  storeNumber: "001",
  eclipseId: "HUASTR001",
  isStoreActive: true,
  addressLine1: "Bantian, Longgang District",
  addressLine2: "",
  city: "Shenzhen",
  stateRegion: "Guangdong",
  postalCode: "518129",
  country: "China",
  storeContact: "Ren Zhengfei Jr.",
  storeTelephone: "999-000-1111",
  storeFax: "999-000-1112",
  storeEmail: "store1@huawei.com",
  storeBuildDate: "2021-06-15",
  storeBuildoutTicketNumber: "HUA001-001",
  associatedProfile: "Huawei Retail",
  serviceProviderStoreId: "HUASZN001",
  eclipseStoreReleaseId: "HUAREL001",
  hideStoreFromAllUsers: false,
  onlyBidOrdersCanBePlaced: false,
  shipToAddressRequired: true,
  fmsBillTo: "HUAFMS001",
  fmsShipTo: "HUAFMS001",
  fmsType: "CLM"
 }
];